spring:
  application:
    name: stock-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always


  jpa:
    hibernate:
      ddl-auto: update

    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

    defer-datasource-initialization: true
    show-sql: true

server:
  port: 8083



