package com.NKP.user_service.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.*;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
public class UserRegistrationDTO {

    @NotBlank(message = "Fullname is required")
    @Size(min = 3, max = 80,message = "Name must be between 3-80 characters" )
    private String fullName;
//    private String userName; // autogenerated

    @NotBlank(message = "password required")
    @Size(min=8, message = "Password must be at least 8 characters")
    @Pattern(
            regexp = "^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d).+$",
            message = "Password must contain uppercase, lowercase and number"
    )
    private String password;

    @NotBlank(message = "Email required")
    @Email(message = "Invalid email format")
    private String emailId;

    @NotBlank(message = "Phone number is required")
    @Pattern(regexp = "^[0-9]{10}$", message = "Phone number must be 10 digits")
    private String phoneNo;

    @Past(message = "DOB must be in the past")
    @JsonProperty("dob")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate dob;


}
